export const data = [
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 2547,
    stepsTarget: 4000,
    performedDate: "15 Oct",
    scheduleDate: "22 Oct",
    calorieIntake: 2547,
    calorieTarget: 2500,
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
    feedback: true,
    date: "22 Oct",
  },
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 1227,
    stepsTarget: 4000,
    performedDate: "20 Oct",
    scheduleDate:
      new Date().getDate() +
      " " +
      new Date().toLocaleString("default", { month: "long" }),
    calorieIntake: 3547,
    calorieTarget: 2500,
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
    feedback: true,
    date: Date.now(),
  },
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 2000,
    stepsTarget: 4000,
    performedDate: "24 Oct",
    scheduleDate: "30 Oct",
    calorieIntake: 1547,
    calorieTarget: 2500,
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
    feedback: false,
    date: "24 Oct",
  },
];
