export const data = [
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 2547,
    stepsTarget: 4000,
    performedDate: "15 Oct",
    scheduleDate: "22 Oct",
    calorieIntake: "2547",
    calorieTarget: "2500",
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
  },
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 2547,
    stepsTarget: 4000,
    performedDate: "15 Oct",
    scheduleDate: "22 Oct",
    calorieIntake: "2547",
    calorieTarget: "2500",
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
  },
  {
    userId: 1,
    name: "Charvie Sharma",
    email: "charviesharma.cs@gmail.com",
    img: "https://bit.ly/dan-abramov",
    stepsWalked: 2547,
    stepsTarget: 4000,
    performedDate: "15 Oct",
    scheduleDate: "22 Oct",
    calorieIntake: "2547",
    calorieTarget: "2500",
    proteinConsumed: 45,
    proteinTarget: 70,
    CarbConsumed: 30,
    carbTarget: 70,
    fatConsumed: 50,
    fatTarget: 70,
  },
];
